from telethon.sync import TelegramClient
from telethon.sessions import StringSession
import colorama
from colorama import Fore, Style

colorama.init(autoreset=True)

api_id = int(input("Enter API ID: "))
api_hash = input("Enter API HASH: ")

try:
    with TelegramClient(StringSession(), api_id, api_hash) as client:
        REBEL_session = client.session.save()
        print(f"RebelBot String Session Given Below\n\n{REBEL_session}")
        client.send_message("me", f" RebelBot String Session Given Below\n\n`{REBEL_session}`")
        client.send_message("me", "This String Generated By @REBELBOT_SUPPORT String Session Generator. Don't Share This String With Anyone!") 
except Exception as e:
    print(f"{e}")
